### ISSUE TITLE
Melhorar a solicitação das datas usando o LocalDate e o LocalTime na classe GerenciaVoo

### ISSUE THREAD

**Issue by natanielsantos** [natanielsantos/TabarajaAirlines#14]
Implementar os métodos das classes  data e hora para melhorar a forma como é solicitada essas informações ao usuário.

**Comment by natanielsantos** [comment]
Essa tarefa não precisa fazer agora. Pode deixar pra fazer depois que terminarmos tudo.

**Comment by SpiritualCrusher** [comment]
Não precisa mexer na classe principal ?

Lançar a modificações das classes e gerenciais criados ? 
Nas novas classes, além do que Edwar, vamos adicionar mais algum item ?

**Comment by natanielsantos** [comment]
Nesse primeiro momento não precisa. Só fazer as novas classes usando a herança... use os atributos do trabalho. Eu estou fazendo o bd e subo o sql em breve...

Os gerencia dessas classes já serão feitos com o bd... então por ora pode criar só as classes mesmo... É mais pra acostumar com o uso do git...

**Comment by SpiritualCrusher** [comment]
Entendi, as classes estão prontas. (todas as classes)

Amanhã estarei realizando a Endoscopia, mas estarei 100% para aula. Eu devo chegar na hora da aula, inclusive. 
Se caso você estranhar alguma atualização ou excesso, estou testando a minha conta. Porque eu dei commit, e não  vi subi nada. Acho que agora as atualizações estão subindo. De qualquer forma levarei o notebook. Se precisar ,passarei na sala mesmo tudo. 
As dúvidas estão surgindo, mas no 'fazer' praticamente estou matando elas. 
Não sei se foi somente eu, mas achei o diagrama de Edwar confuso.

**Comment by natanielsantos** [comment]
Blz. Estarei lah hoje aí a gente conversa.
Não se preocupe a ideia é justamente ir fazendo pra acostumar com os commit
e pull... Jà terminei a base de dados vou subi-la depois que confirmar seus
commits...

2016-05-25 0:07 GMT-03:00 SpiritualCrusher notifications@github.com:

**Comment by natanielsantos** [comment]
Realmente aqui não mudou nada... só pra lembrar:
- commit manda para o seu repositório na sua própria máquina.
- push envia o que você mudou para o fork na sua conta no git...
- pull request é o que vai mandar o que mudou da sua conta para a minha. Essa é a ordem...
